apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: post-installation
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/Howard-Luo/non-olm-cp4d-gitops.git
    targetRevision: main
    path: 9-post-installation
    kustomize: {}
  project: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
